title: IoT Specialist
description: Research interests encompass Wireless Sensor Networks (WSN), Internet of Things (IoT), Unmanned Aerial Vehicles (UAVs), Smart Homes, Smart Cities and AIOT.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Personal Information for your Resume
email: songsheng.LI@hotmail.com
linkedin_username: yourlinkedin
github_username: pineson
